# 行为树导航参数
behavior_server:
  ros__parameters:
    bt_loop_duration: 100
    default_server_timeout: 20
    num_entries_per_port: 10
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    
    # 行为树文件路径
    bt_xml_filename: "config/behavior_trees/navigate_to_pose_w_replanning.xml"
    
    # 恢复行为参数
    recoveries:
      spin:
        plugin: "nav2_recoveries/Spin"
        simulate_ahead_time: 2.0
        max_rotational_vel: 1.0
        min_rotational_vel: 0.4
        rotational_acc_lim: 3.2
        
      backup:
        plugin: "nav2_recoveries/BackUp"
        backup_dist: 0.15
        backup_speed: 0.025
        
      wait:
        plugin: "nav2_recoveries/Wait"
        wait_duration: 5.0
