# 全局规划器参数
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
      planner_downsampling_factor: 1
      interpolation_resolution: 0.1
      use_final_approach_orientation: true
      visualize_expansions: false
      cost_factor: 3.0
      neutral_cost: 50
      lethal_cost: 253
      publish_expansion: false
      
    # 备用规划器
    Smac2D:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      motion_model_for_search: "MOORE"
      angle_quantization_bins: 72
      minimum_turning_radius: 0.2
      cache_obstacle_heuristic: true
      reverse_penalty: 2.0
      change_penalty: 0.15
      non_straight_penalty: 1.2
      cost_penalty: 2.0
      analytic_expansion_max_length: 3.0
      analytic_expansion_ratio: 3.5
